# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site Settings
# ================================
title: Shao-Chun Lu - Backend Developer
description: >- # this means to ignore newlines until "baseurl:"
  Personal resume website of Shao-Chun Lu, a Backend Developer with expertise in Python, Go, TypeScript, and distributed systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oslo0322.github.io" # the base hostname & protocol for your site

# Build settings
# ================================
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: Asia/Taipei

# Exclude from processing
# ================================
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins
# ================================
plugins:
  - jekyll-feed
  - jekyll-sitemap

# GitHub Pages settings
# ================================
github: [metadata]

# Collections
# ================================
collections:
  resume:
    output: true
    permalink: /:name/

# Defaults
# ================================
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "resume"
    values:
      layout: "resume"
